services:
  - type: web
    name: shop2you
    env: node
    plan: free
    buildCommand: npm install && npm run build:css
    startCommand: npm start
    envVars:
      - key: SESSION_SECRET
        generateValue: true
